### ISSUE TITLE
Connection pool shut down

### ISSUE THREAD

**Issue by lvxincao** [bbossgroups/bboss-elasticsearch#51]
请求过多的时候，会出现以下错误
org.frameworkset.elasticsearch.ElasticSearchException: java.lang.IllegalStateException: Connection pool shut down
Caused by: java.lang.IllegalStateException: Connection pool shut down
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.pool.AbstractConnPool.lease(AbstractConnPool.java:191)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:267)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
	at org.frameworkset.spi.remote.http.HttpRequestUtil.sendBody(HttpRequestUtil.java:1285)
	at org.frameworkset.spi.remote.http.HttpRequestUtil.sendJsonBody(HttpRequestUtil.java:1264)Disconnected from the target VM, address: '127.0.0.1:49503', transport: 'socket'

	at org.frameworkset.elasticsearch.client.RestSearchExecutorUtil.__executeHttp(RestSearchExecutorUtil.java:67)
	at org.frameworkset.elasticsearch.client.RestSearchExecutor.executeHttp(RestSearchExecutor.java:115)
	at org.frameworkset.elasticsearch.client.ElasticSearchRestClient$3.execute(ElasticSearchRestClient.java:771)
	at org.frameworkset.elasticsearch.client.ElasticSearchRestClient._executeHttp(ElasticSearchRestClient.java:940)
	... 61 more

**Comment by yin-bp** [comment]
是不是基于容器环境，如果是的话，估计是因负载过高，进程自动重启或者重新部署导致，

在重启过程中bboss使用的连接池会自动释放关闭，但是进程还在接收请求，这个时候请求无法处理，从而报错

**Comment by yin-bp** [comment]
@lvxincao 建议升级到bboss最新版本：
https://esdoc.bbossgroups.com/#/changelog
